### ISSUE TITLE
P-01 Саморегистрация

### ISSUE THREAD

**Issue by cadfoot** [kafitimi/multimeter#2]
Как будут регистрироваться участники? Администраторы?
Какие поля должны включать окна регистрации в обоих случаях?

**Comment by volodya-leveryev** [comment]
1. Новые администраторы создаются другими администраторами.
2. Участники могут быть созданы администраторами.
3. Администратор может разрешить регистрацию в настройках контеста.
4. Если участник не зарегистрирован, тогда он должен видеть перечень контестов с открытой регистрацей. Выбрав контест с открытой регистрацией участник переходит к странице регистрации, где вводит свои данные.
5. Перечень полей данных участника единый для всех контестов:
- username (логин)
- last_name (фамилия
- first_name (имя)
- patronymic_name (отчество)
- birthday (дата рождения)
- email
6. Администратор может разрешить участнику одного контеста участвовать в другом контесте.

**Comment by cadfoot** [comment]
Т.е. профиль участника будет в рамках одного контеста, а не всего сервиса?

**Comment by volodya-leveryev** [comment]
Профиль участника один на всю систему.
Профиль связан с контестами связью "Многие ко многим".
Профиль участника может быть создан 2 способами:

1. Профиль создан администратором.
2. Профиль создан участником при регистрации в контесте где разрешена регистрация. При этом новый профиль автоматически связывается с выбранным контестом. 

Администратор может вручную добавить связь между профилем участника и контестом.

**Comment by av-pavlov** [comment]
надо бы в карточки

**Comment by av-pavlov** [comment]
- Добавить связь "многие-ко-многим" Account-Contest  в модели
- Добавить на главную список тех контестов, на которые уже зарегистрирован текущий пользователь, плюс тех, где разрешена саморегистрация.
- Добавить форму саморегистрации
- Добавить редактирование списка участников контеста для админа.

**Comment by cadfoot** [comment]
@av-pavlov 
> * Добавить редактирование списка участников контеста для админа.

имхо эта задача выходит за рамки данного тикета.

**Comment by cadfoot** [comment]
@wowace
