### ISSUE TITLE
A-13 Импорт задачи из Polygon

### ISSUE THREAD

**Issue by av-pavlov** [kafitimi/multimeter#28]
**Автор** может импортировать / экспортировать задачи. Система должна позволять импортировать задачи в формате Polygon. Ниже прикреплен файл с содержимым пакета Полигона.
[contest-6124.zip](https://github.com/kafitimi/multimeter/files/1828104/contest-6124.zip)

**Comment by cadfoot** [comment]
Можно ли будет кормить импортеру архив, или нужно его перед этим распаковать?

**Comment by cadfoot** [comment]
@wowace @av-pavlov в модели Олимпиада есть поля с указанием путей к файлу с условиями и с правилами. Где будут храниться сами файлы?

**Comment by cadfoot** [comment]
как должен происходить процесс импорта? Будет ли вестись динамический лог во время процесса?

**Comment by av-pavlov** [comment]
Для каждой олимпиады будет создаваться рабочая папка. В ней хранятся скомпилированные условия, тесты и чекер, готовые к использованию. А так, возможно, задачи хранятся по отдельности в зипах или еще как-то.  

Что такое динамический лог?

**Comment by cadfoot** [comment]
У нас же всё в бы должно хранится, так предполагали ранее. Сейчас,
например, модель задачи имеет поле для условия задачи (нескомпилированное).
Было бы лучше, имхо, использовать эту же модель.
Про дин. лог: так как импорт - процесс не мгновенный, думаю, стоит
показывать его ход, в том, или ином виде.

вт, 3 апр. 2018 г. в 15:37, av-pavlov <notifications@github.com>:

**Comment by av-pavlov** [comment]
Хорошо, если прогресс будет, но это не первоочередная проблема.

Все хранится в базе - как на складе. А когда делается контест, задачи разворачиваются "в боевое положение" в папке контеста. Условия у каждой задачи свое, все задачи контеста надо собирать, например, для компиляции в единый PDF. 

Правила/положение также у каждого контеста свои.

**Comment by cadfoot** [comment]
Про логи я не настаиваю - мысля такая пришла просто.
Сейчас можно «кормить» архив с контестом, содержимое распаковывается во
временную папку и обрабатывается - генерятся ответы для тестов. Ну и
парсится xml. Правда, полезной информации в xml файле контеста нет, но это
не важно. Можно будет потом архив с одной задачей использовать, ну и в бд
как-то добавлять всю эту историю. Пока лишь так. Ветка в репозитории есть -
polygon_import

вт, 3 апр. 2018 г. в 22:21, av-pavlov <notifications@github.com>:

**Comment by cadfoot** [comment]
@av-pavlov @wowace 
### Что?
Можно уже говорить, что импортирование работает.
### Где?
Ветка polygon_import. 
### Как?
На странице "Список задач" появилась кнопка "Импорт".

Можно кидать архив задачи, так и архив контеста. В случае с последним контест не создается, лишь импортируются её задачи. При импортировании можно выбрать предпочтительный язык для условий и решения. Ошибки также обрабатываются.
Все происходит на основном потоке (пока). Тестировал архив контеста с 4 полными задачами, процесс длится меньше секунды (i7-7500u, ssd). Рекомендую проверить на вашем железе.

**Comment by av-pavlov** [comment]
closed in fc2aeea7ca74ff045cc1ef35db74ded838853513 (branch polygon_import merged)
