### ISSUE TITLE
What is the point of using fancy-forms.js?

### ISSUE THREAD

**Issue by cadfoot** [kafitimi/multimeter#3]

**Comment by volodya-leveryev** [comment]
1. Поля ввода в формах Django не имеют CSS-классов оформления. Этот JS-код должен добавить их. 
2. Виджеты в формах Django выводятся в таблицу или в параграфы. Этот JS-код переносит их в подготовленные div-ы.

Таким образом, формы Django начинают соответствовать рекомендациям Bootstrap.
